development:
  adapter: mysql2
  database: crs_development
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: crs_production
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: crs_test
  username: root
  password:
  host: localhost
  encoding: utf8
